name: zufaling
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_pose_detection: ^0.5.0
  camera: ^0.10.0
  video_player: ^2.6.1
  fluttertoast: ^8.0.8
  flutter_native_splash: ^2.2.19
  sqflite: ^2.2.7
  path_provider: ^2.0.5
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#fe5623"
  color_dark: "#000000"
  image: "assets/images/logo.png"
  image_dark: "assets/images/logo.png"
  branding: assets/images/brand.png

  android_12:
    color: "#fe5623"
    color_dark: "#000000"
    image: "assets/images/logo.png"
    icon_background_color: "#fe5623"
    image_dark: "assets/images/logo.png"
    icon_background_color_dark: "#000000"
    branding: assets/images/brand.png

  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/prueba.mp4
    - assets/images/r1.jpg